
exports.INIT_DATABASE_SQL = `
CREATE DATABASE IF NOT EXISTS koamy DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
`
exports.INIT_USER_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS users(
name VARCHAR(100) NOT NULL COMMENT '姓名',
avator VARCHAR(100) NOT NULL COMMENT '用户头像'
);
`
